src/main/java/com/projectw/domain/user/entitiy/User.java

Feat/dining init 생성

---

src/main/java/com/projectw/domain/waiting/controller/WaitingController.java
src/main/java/com/projectw/domain/waiting/entity/Waiting.java
src/main/java/com/projectw/domain/waiting/enums/WaitingStatus.java
src/main/java/com/projectw/domain/waiting/repository/WaitingRepository.java
src/main/java/com/projectw/domain/waiting/repository/WaitingRepositoryQuery.java
src/main/java/com/projectw/domain/waiting/repository/WaitingRepositoryQueryImpl.java
src/main/java/com/projectw/domain/waiting/service/WaitingService.java

[init] waiting 기본 틀 잡기

---

src/main/java/com/projectw/domain/waiting/entity/Waiting.java

개인 컴으로 돌아가는거 확인완료 했고 빠진 컬럼 있어서 넣었습니다.
>

[update] WaitingStatus 추가

---

src/main/java/com/projectw/domain/store/dto/request/StoreRequestDto.java
src/main/java/com/projectw/domain/store/dto/response/StoreResponseDto.java
src/main/java/com/projectw/domain/store/entity/Store.java
src/main/java/com/projectw/domain/store/service/StoreOwnerServiceImpl.java

reservation_table_count 인한 오류 수정

Feat/dining fix reservation_table_count 추가된 부분 수정

---

src/main/java/com/projectw/domain/auth/controller/AuthController.java
src/main/java/com/projectw/domain/auth/service/AuthService.java

> 포스트맨 테스트 편의를 위해 헤더에 리프레쉬 토큰과 엑세스 토큰을 담았습니다.

[feat] 토큰 헤더에 담아주기

---

src/main/java/com/projectw/domain/store/controller/StoreUserController.java
src/main/java/com/projectw/domain/store/repository/StoreRepository.java
src/main/java/com/projectw/domain/store/service/StoreUserService.java
src/main/java/com/projectw/domain/store/service/StoreUserServiceImpl.java

store 이름으로 검색 기능 생성
> store pagenation 적용, store 이름으로 검색 기능 생성

[update] store pagenation 적용, store 이름으로 검색 기능 생성

---

src/main/java/com/projectw/domain/store/dto/request/StoreRequestDto.java
src/main/java/com/projectw/domain/store/dto/response/StoreResponseDto.java
src/main/java/com/projectw/domain/store/entity/Store.java
src/main/java/com/projectw/domain/store/service/StoreOwnerServiceImpl.java

Feat/dining deposit추가

---

src/main/java/com/projectw/common/config/WebSecurityConfig.java
src/main/java/com/projectw/domain/waiting/controller/WaitingQueueUserController.java
src/main/java/com/projectw/domain/waiting/dto/WaitingQueueResponse.java
src/main/java/com/projectw/domain/waiting/service/WaitingQueueService.java

> 유저가 웨이팅 대기열에 등록되어있는지 확인하는 api 추가

[feat] 유저가 웨이팅 대기열에 등록되어있는지 확인하는 api 추가

---

src/main/java/com/projectw/domain/waiting/controller/WaitingQueueUserController.java

[update] api 주소 오타 수정

---

Dockerfile
rediscluster/docker-compose.yml

[update] 도커 파일 추가

---

src/main/java/com/projectw/common/config/WebSecurityConfig.java
src/main/java/com/projectw/common/controller/HealthCheckController.java
src/main/java/com/projectw/security/SecurityFilter.java

[update] 헬스체크 api 추가

---

src/main/java/com/projectw/common/config/RedisConfig.java
src/main/java/com/projectw/domain/notification/client/MessageClient.java
src/main/java/com/projectw/domain/redis/RedisHealthCheckScheduler.java

> 레디스 클러스터의 노드가 죽으면 슬랙으로 알림메세지 보내도록 로직 구현

[feat] 레디스 상태체크 알림 스케쥴러 추가

---

src/main/java/com/projectw/common/enums/Category.java
src/main/java/com/projectw/domain/store/dto/response/CategoryMapper.java
src/main/java/com/projectw/domain/store/dto/response/CategoryMapperValue.java
src/main/java/com/projectw/domain/store/entity/Store.java
src/test/java/com/projectw/common/enums/CategoryTest.java

[feat] 카테고리 추가

---

README.md

[update] readme 1차 수정

---

src/main/java/com/projectw/common/config/RedisConfig.java
src/main/java/com/projectw/common/enums/ResponseCode.java
src/main/java/com/projectw/domain/menu/repository/MenuRepository.java
src/main/java/com/projectw/domain/payment/service/PaymentService.java
src/main/java/com/projectw/domain/reservation/controller/ReservationController.java
src/main/java/com/projectw/domain/reservation/dto/ReserveRequest.java
src/main/java/com/projectw/domain/reservation/dto/ReserveResponse.java
src/main/java/com/projectw/domain/reservation/entity/Reservation.java
src/main/java/com/projectw/domain/reservation/entity/ReservationMenu.java
src/main/java/com/projectw/domain/reservation/event/ReservationInsertEvent.java
src/main/java/com/projectw/domain/reservation/event/handler/ReservationEventListener.java
src/main/java/com/projectw/domain/reservation/exception/InvalidCartException.java
src/main/java/com/projectw/domain/reservation/repository/ReservationMenuRepository.java
src/main/java/com/projectw/domain/reservation/service/ReservationService.java

[update] reservationMenu 추가 작업 완료

---

src/main/java/com/projectw/domain/crawler/service/CrawlerService.java

feat. 크롤링 레디스 추가

---

src/main/java/com/projectw/domain/follow/service/FollowService.java

[update] 팔로우 리팩토링

---

src/main/java/com/projectw/domain/chatbot/controller/ChatbotController.java
src/main/java/com/projectw/domain/chatbot/dto/request/ChatbotRequestDto.java
src/main/java/com/projectw/domain/chatbot/dto/response/ChatbotResponseDto.java
src/main/java/com/projectw/domain/chatbot/service/ChatbotService.java
src/main/java/com/projectw/domain/chatbot/service/InquiryDetailHandler.java
src/main/java/com/projectw/domain/chatbot/service/InquiryType.java
src/main/java/com/projectw/domain/chatbot/service/MemberInquiryDetail.java
src/main/java/com/projectw/domain/chatbot/service/MemberInquiryHandler.java
src/main/java/com/projectw/domain/chatbot/service/PaymentInquiryDetail.java
src/main/java/com/projectw/domain/chatbot/service/PaymentInquiryHandler.java
src/main/java/com/projectw/domain/chatbot/service/ReservationInquiryDetail.java
src/main/java/com/projectw/domain/chatbot/service/ReservationInquiryHandler.java

[update] 챗봇 리팩토링(한글->영어,클래스 분리)

---

src/main/java/com/projectw/domain/menu/service/MenuService.java

[update] 메뉴 리팩토링

---

src/main/java/com/projectw/domain/menu/service/MenuService.java
src/main/java/com/projectw/domain/store/entity/Store.java

[update] 메뉴 권한 메서드 수정

---

src/main/java/com/projectw/common/config/ElasticsearchConfig.java
src/main/java/com/projectw/domain/search/SearchService.java
src/main/java/com/projectw/domain/search/StoreDoc.java
src/main/resources/application-dev.yml

> 엘라스틱 서치 통합검색 정확도 향상을 위해 쿼리를 수정하였습니다.

[feat] 엘라스틱 서치 검색 정확도 향상을 위해 쿼리 튜닝

---

src/main/java/com/projectw/common/config/S3Service.java
src/main/java/com/projectw/domain/store/controller/StoreOwnerController.java
src/main/java/com/projectw/domain/store/controller/StoreUserController.java
src/main/java/com/projectw/domain/store/dto/response/StoreLikeResposeDto.java
src/main/java/com/projectw/domain/store/dto/response/StoreResponseDto.java
src/main/java/com/projectw/domain/store/entity/Store.java
src/main/java/com/projectw/domain/store/repository/StoreLikeRepository.java
src/main/java/com/projectw/domain/store/service/StoreOwnerService.java
src/main/java/com/projectw/domain/store/service/StoreOwnerServiceImpl.java
src/main/java/com/projectw/domain/store/service/StoreUserService.java
src/main/java/com/projectw/domain/store/service/StoreUserServiceImpl.java

> store 이미지 업로드 기능 추가, 좋아요, 조회수 기능 추가

[update] store 이미지 업로드 기능 추가, 좋아요, 조회수 기능 추가

---

src/main/java/com/projectw/domain/crawler/service/CrawlerService.java
src/main/java/com/projectw/domain/review/service/ReviewService.java

feat. 크롤링 ec2 프록시기반 ip변경 기능 추가

---

src/main/java/com/projectw/domain/store/service/StoreUserServiceImpl.java

Feat/storelike store like와 view에 분산락 적용

---

src/main/java/com/projectw/domain/reservation/service/ReservationService.java

[update] 장바구니 담기 수정

---

src/main/java/com/projectw/domain/menu/controller/MenuOwnerController.java
src/main/java/com/projectw/domain/menu/controller/MenuUserController.java
src/main/java/com/projectw/domain/menu/dto/request/MenuRequestDto.java
src/main/java/com/projectw/domain/menu/dto/response/MenuResponseDto.java
src/main/java/com/projectw/domain/menu/service/MenuService.java

[update] 메뉴 Dto 형식 변경

---

src/test/java/com/projectw/domain/menu/MenuServiceTest.java

[update] 메뉴 서비스 테스트 패키지 수정

---

src/main/java/com/projectw/domain/category/DistrictCategory.java

[fix] 카테고리 code 중복 수정

---

src/main/resources/application-dev.yml
src/main/resources/application-elastic.yml
src/main/resources/application-test.yml

[feat] 엘라스틱 서치 배포 url로 수정

---

src/main/java/com/projectw/domain/follow/controller/FollowController.java

[update] 팔로우한 유저 가게 좋아요 목록 조회 반환값 수정

---

src/main/java/com/projectw/security/SecurityFilter.java

[feat] request 시 log 안나오도록

---

.github/workflows/pr-action.yml
src/test/java/com/projectw/domain/payment/service/PaymentServiceTest.java

[feat] githubaction 시크릿 추가

---

README.md

[update] README 수정

---

src/test/java/com/projectw/domain/waiting/service/WaitingQueueServiceTest.java

[feat] 웨이팅 대기열 테스트 코드 수정

---

src/test/java/com/projectw/domain/waiting/service/WaitingQueueServiceTest.java

[fix] 웨이팅 테스트 실패 수정

---

README.md
src/main/java/com/projectw/domain/store/entity/StoreLike.java

Feat/storelike store like 인덱스 추가

---

src/main/java/com/projectw/domain/reservation/controller/CartController.java
src/main/java/com/projectw/domain/reservation/controller/ReservationController.java

[update] 장바구니 분리 작업

---

src/main/java/com/projectw/domain/crawler/service/CrawlerService.java

feat. 프록시 아이피 변경

---

src/main/java/com/projectw/domain/store/repository/StoreLikeRepository.java

[fix] 음식점 조회시 좋아요 아닌 음식점 문제 해결
